### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by KingKnecht** [sid-code/boolalg#1]
Hi,

I'm facing following compile errors in boolalg.nim:

1. Line 59:
`let realComment = if isNil(comment): simpl.history[^1].comment else: comment`
gives me:

> Error: type mismatch: got <nil> but expected 'string'

Tried to fix it with:
`let realComment = if (comment == ""): simpl.history[^1].comment else: comment`

2. Line 55:
`proc addSubstep(simpl: BExpSimplifier, subSimpl: BExpSimplifier, comment: string = nil) =`
gives me:

> Error: type mismatch: got <nil> but expected 'string'

tried to fix it with:
 `proc addSubstep(simpl: BExpSimplifier, subSimpl: BExpSimplifier, comment: string = "") =`

3. Line 71:
`      s.write(step.substep, indent + 1)`
gives me:
`Error: type mismatch: got <BExpSimplifier>`

Any ideas on this?
Thx,
Sven

edit:
Nim Compiler Version 0.20.2 [Windows: amd64]

**Comment by sid-code** [comment]
The compiler updated since I stopped working on this and broke backwards compatibility more than once. I've fixed these issues, and everything should work with the latest stable Nim now (0.20.2).
